project_id = "qsfotrjvjsuxfzagcmzz"

[functions.create-priority-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.purchase-prestream-spot]
verify_jwt = false

[functions.verify-spot-payment]
verify_jwt = false

[functions.stream-signal]
verify_jwt = false

[functions.process-bid]
verify_jwt = false

[functions.verify-bid-payment]
verify_jwt = false

[functions.send-bid-notification]
verify_jwt = false
